ccflags-y += -Idrivers/media/platform/msm/camera_v2_serranove
ccflags-y += -Idrivers/media/platform/msm/camera_v2_serranove/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_serranove/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
