ccflags-y += -Idrivers/media/platform/msm/camera_v2_serranove
ccflags-y += -Idrivers/media/platform/msm/camera_v2_serranove/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_serranove/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
obj-$(CONFIG_MSM_OTP) += msm_otp.o
